<h1 class="mb-4">Roles</h1>

<?php

/**
 * @var \MyCompany\RegistrationModule\Block\SummaryBlock $this
 */

$url = $this->getViewFileUrl('MyCompany_RegistrationModule::css/style.css');
if ($url):
    echo '<link href="'.$url.'" rel="stylesheet" type="text/css" media="all" />';
endif;
?>

<?php if ($this->getRegistrations()->getSize() > 0): ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Role</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getRegistrations() as $registration): ?>
            <tr>
                <td><?= $registration->getName(); ?></td>
                <td><?= $registration->getRole(); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="alert alert-warning" role="alert">
        No registrations found.
    </div>
<?php endif; ?>




