<?php
$employeeCollection = $this->getData('employeeCollection');
?>

<table class="data-table admin__control-table">
    <thead>
    <tr>
        <th><?php echo __('ID'); ?></th>
        <th><?php echo __('Name'); ?></th>
        <th><?php echo __('Email'); ?></th>
        <th><?php echo __('Image'); ?></th>
        <th><?php echo __('Action'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($employeeCollection as $employee): ?>
        <tr>
            <td><?php echo $employee->getId(); ?></td>
            <td><?php echo $employee->getName(); ?></td>
            <td><?php echo $employee->getEmail(); ?></td>

            <td>
                <?php if ($employee->getImage()): ?>
                    <?php
                    $mediaUrl = $this->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . $employee->getImage();
                    echo '<img src="' . $mediaUrl . '" alt="' . $employee->getName() . '" width="100"/>';
                    ?>
                <?php else: ?>
                    <?php echo __('No Image'); ?>
                <?php endif; ?>
            </td>


            <td>
                <a href="<?php echo $this->getUrl('registrationmodule/admin1/edit', ['id' => $employee->getId()]); ?>"><?php echo __('Edit'); ?></a>
                &nbsp;|&nbsp;
                <a href="<?php echo $this->getUrl('registrationmodule/admin1/delete', ['id' => $employee->getId()]); ?>"
                   onclick="return confirm('<?php echo __('Are you sure you want to delete this employee?'); ?>');">
                    <?php echo __('Delete'); ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <?php echo $this->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . $employee->getImage(); ?>

</table>
